version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run lint
          command: yarn -s lint

workflows:
  version: 2
  build:
    jobs:
      - test
